# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://sanjeevchiremath.github.io/linalgebra/"

git_url = "https://github.com/sanjeevchiremath/linalgebra/tree/master/"

def custom_doc_links(name): return None
